### ISSUE TITLE
Port Eigenvalue/Eigenvector decompositions from R2SymTensor

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/LvArray#178]
@andrembcosta  needs the spectral decompositions that used to live in R2SymTensor before it was removed from the code for phase field fracture.

**Comment by corbett5** [comment]
Both the eigenvalues and vectors I presume?

**Comment by rrsettgast** [comment]
yes. Remember that the old R2SymTensor were in funny non-Voigt ordering.

**Comment by corbett5** [comment]
So I've found two slightly different algorithms for computing the eigenvalues of a symmetric 3x3 matrix.

The first is basically what was in the `R2SymTensor`
https://en.wikipedia.org/wiki/Eigenvalue_algorithm#3.C3.973_matrices

The second is what Eigen uses
http://eigen.tuxfamily.org/dox/SelfAdjointEigenSolver_8h_source.html
http://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html#afe520161701f5f585bcc4cedb8657bd1

Note:
```
For the 3x3 case, we observed the following worst case relative error regarding the eigenvalues:

    double: 1e-8
    float: 1e-3
```

They both use a call to `sqrt` and three calls to trig functions. Assuming the Eigen tolerance is acceptable (I have no idea what the wikipedia algorithm's tolerance is) I favor the Eigen algorithm because it has no branching and simply because it's in Eigen.

Finally there's this third algorithm that is *probably* the fastest since it has no trig stuff and only calls to the approximate inverse square root but looks like someone took spaghetti and threw it in a food processor.
https://github.com/smidm/Singular-Value-Decomposition/blob/master/Singular_Value_Decomposition_Main_Kernel_Body.hpp#L91
